name: one_school
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  #Router
  go_router: ^6.2.0
  #Network
  dio: ^5.0.1
  #Riverpod
  flutter_riverpod: ^2.3.0
  riverpod_annotation: ^2.0.0
  #Freezed
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  #Hive
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.0
  #Animations
  flutter_animate: ^4.1.0
  #Others
  permission_handler: ^10.2.0
  flutter_svg: ^2.0.2
  google_fonts: ^4.0.3
  url_strategy: ^0.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^2.0.0
  freezed: ^2.3.2
  build_runner: ^2.3.3
  json_serializable: ^6.6.1
  riverpod_generator: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/svg/
    - google_fonts/

  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
