name: OneSchool

on:
  push:
    branches: [action]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
      - uses: erickzanardo/flutter-gh-pages@v7
        with:
          targetBranch: action
          baseHref: /OneSchool/
  
